<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/06/19 15:16:36
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
