<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/06/18 16:51:47
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'login',
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
);
