<?php


/**
 * Skeleton subclass for performing query and update operations on the 'jobeet_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 06/12/20 08:42:31
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetCategoryPeer extends BaseJobeetCategoryPeer {

    /**
     * @return array
     * @throws PropelException
     */
    static public function getWithJobs()
    {
        $criteria = new Criteria();
        $criteria->addJoin(self::ID, JobeetJobPeer::CATEGORY_ID);
        $criteria->add(JobeetJobPeer::EXPIRES_AT, time(), Criteria::GREATER_THAN);
        $criteria->add(JobeetJobPeer::IS_ACTIVATED, true);
        $criteria->setDistinct();

        return self::doSelect($criteria);
    }
    static public function getForSlug($slug)
    {
      $criteria = new Criteria();
      $criteria->add(self::SLUG, $slug);
     
      return self::doSelectOne($criteria);
    }

} // JobeetCategoryPeer
